### ISSUE TITLE
提个小建议

### ISSUE THREAD

**Issue by Bromaomao** [resphinas/claude-on-wechat#3]
如果把@bot放在问题后面，他会把整段都识别进去然后回答不上，请问能不能优化一下呢

**Comment by resphinas** [comment]
为什么要把@bot放问题后面

**Comment by Bromaomao** [comment]
> 用前缀就好了，这个改动没有意义，不过还是谢谢你的建议

好的 因为我在群里使用 总有些朋友喜欢@放到后面的
