### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Bromaomao** [resphinas/claude-on-wechat#5]
前两天还好好的，今天突然报错，我测了一下claude_api，发现也报错
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\claude\claude_api.py", line 132, in <module>
    main(org_uuid,con_uuid,cookie)
  File "C:\Users\Administrator\Desktop\claude\claude_api.py", line 108, in main
    answer,cache = get_last_answer(history, cache)
  File "C:\Users\Administrator\Desktop\claude\claude_api.py", line 75, in get_last_answer
    for i in history["chat_messages"]:
KeyError: 'chat_messages'

**Comment by resphinas** [comment]
可以尝试换一下参数，或者 vpn切到美国

**Comment by Bromaomao** [comment]
> 可以尝试换一下参数，或者 vpn切到美国

参数调过了，梯子也换了几个美国节点，官网能进去正常聊天，看报错是没找到“chat_messages”

**Comment by resphinas** [comment]
方便远程吗？让我找找原因。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月16日(周三) 中午1:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [resphinas/claude-on-wechat] 报错 (Issue #5)




  
可以尝试换一下参数，或者 vpn切到美国
  
参数调过了，梯子也换了几个美国节点，官网能进去正常聊天，看报错是没找到“chat_messages”

**Comment by Bromaomao** [comment]
> 方便远程吗？让我找找原因。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年8月16日(周三) 中午1:37 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [resphinas/claude-on-wechat] 报错 (Issue #5) 可以尝试换一下参数，或者 vpn切到美国 参数调过了，梯子也换了几个美国节点，官网能进去正常聊天，看报错是没找到“chat_messages” — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

抱歉白天忙去了，你那边测试是正常的吗，可以加个联系方式

**Comment by resphinas** [comment]
官网做了个新的加密...等我更新

**Comment by resphinas** [comment]
已更新，可以正常使用

**Comment by Bromaomao** [comment]
> 已更新，可以正常使用

请问下用的execjs哪个版本的库，我安装了最新版说语法错误
